# Copyright (c) 2026 NyxeraLabs
# Author: José María Micoli
# Licensed under BSL 1.1
# Change Date: 2033-02-17 → Apache-2.0
#
# You may:
# ✔ Study
# ✔ Modify
# ✔ Use for internal security testing
#
# You may NOT:
# ✘ Offer as a commercial service
# ✘ Sell derived competing products
#
# You may:
# ✔ Study
# ✔ Modify
# ✔ Use for internal security testing
#
# You may NOT:
# ✘ Offer as a commercial service
# ✘ Sell derived competing products

-- Auto-generated from vectorvue.db sqlite schema
-- Generated by scripts/export_pg_schema.py
SET client_min_messages TO WARNING;

CREATE TABLE IF NOT EXISTS "action_risk_log" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "operator" TEXT NOT NULL,
    "technique" TEXT NOT NULL,
    "target_id" TEXT NOT NULL,
    "risk_score" DOUBLE PRECISION NOT NULL,
    "risk_level" TEXT NOT NULL,
    "evaluated_at" TEXT NOT NULL,
    "action_taken" TEXT DEFAULT NULL,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "actions" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "asset_id" BIGINT,
    "mitre_technique" TEXT,
    "command" TEXT,
    "result" TEXT,
    "operator" TEXT,
    "timestamp" TEXT,
    "detection" TEXT,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "activity_log" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "actor" TEXT NOT NULL,
    "action_type" TEXT NOT NULL,
    "target_type" TEXT,
    "target_id" TEXT,
    "timestamp" TEXT NOT NULL,
    "context_json" TEXT,
    "severity" TEXT DEFAULT 'info',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "actor_ttps" (
    "id" BIGSERIAL,
    "actor_id" BIGINT NOT NULL,
    "mitre_technique" TEXT NOT NULL,
    "frequency" TEXT DEFAULT 'common',
    "last_observed" TEXT,
    "confidence" DOUBLE PRECISION DEFAULT 0.5,
    "evidence" TEXT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_actor_ttps_1" ON "actor_ttps" ("actor_id", "mitre_technique");
CREATE TABLE IF NOT EXISTS "anomaly_detections" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "detection_timestamp" TEXT NOT NULL,
    "anomaly_type" TEXT NOT NULL,
    "severity" TEXT DEFAULT 'MEDIUM',
    "description" TEXT NOT NULL,
    "baseline_expectation" TEXT,
    "observed_behavior" TEXT,
    "likelihood_score" DOUBLE PRECISION DEFAULT 0.5,
    "remediation_suggested" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "api_integrations" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "integration_name" TEXT NOT NULL,
    "api_type" TEXT NOT NULL,
    "api_endpoint" TEXT,
    "api_key_hash" TEXT,
    "enabled" BIGINT DEFAULT 1,
    "sync_frequency_minutes" BIGINT DEFAULT 60,
    "last_sync" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_api_integrations_1" ON "api_integrations" ("campaign_id", "integration_name");
CREATE TABLE IF NOT EXISTS "assets" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "os" TEXT,
    "tags" TEXT,
    "first_seen" TEXT,
    "last_seen" TEXT,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "audit_certification_reports" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "report_type" TEXT NOT NULL,
    "generated_at" TEXT NOT NULL,
    "generated_by" TEXT NOT NULL,
    "framework" TEXT,
    "total_requirements" BIGINT DEFAULT 0,
    "satisfied_requirements" BIGINT DEFAULT 0,
    "certification_status" TEXT DEFAULT 'incomplete',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "audit_log" (
    "id" TEXT,
    "timestamp" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "target_type" TEXT NOT NULL,
    "target_id" TEXT DEFAULT '',
    "old_value_hash" TEXT DEFAULT '',
    "new_value_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_audit_log_1" ON "audit_log" ("id");
CREATE TABLE IF NOT EXISTS "audit_verification_chain" (
    "id" BIGSERIAL,
    "audit_log_id" BIGINT NOT NULL,
    "verified_at" TEXT NOT NULL,
    "verified_by" TEXT NOT NULL,
    "chain_hash" TEXT NOT NULL,
    "verification_method" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "behavioral_profiles" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "profile_name" TEXT NOT NULL,
    "baseline_technique" TEXT NOT NULL,
    "avg_execution_time" DOUBLE PRECISION DEFAULT 0.0,
    "avg_detection_likelihood" DOUBLE PRECISION DEFAULT 0.5,
    "success_rate" DOUBLE PRECISION DEFAULT 0.0,
    "variance" DOUBLE PRECISION DEFAULT 0.1,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_behavioral_profiles_1" ON "behavioral_profiles" ("campaign_id", "profile_name");
CREATE TABLE IF NOT EXISTS "c2_infrastructure" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "node_name" TEXT NOT NULL,
    "node_type" TEXT DEFAULT 'listener',
    "exposure_score" DOUBLE PRECISION DEFAULT 0.0,
    "reputation_score" DOUBLE PRECISION DEFAULT 0.0,
    "burn_probability" DOUBLE PRECISION DEFAULT 0.0,
    "burn_level" TEXT DEFAULT 'fresh',
    "should_rotate" BIGINT DEFAULT 0,
    "last_rotated" TEXT,
    "notes" TEXT DEFAULT '',
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_c2_infrastructure_1" ON "c2_infrastructure" ("campaign_id", "node_name");
CREATE TABLE IF NOT EXISTS "campaign_metrics" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "metric_timestamp" TEXT NOT NULL,
    "total_assets" BIGINT DEFAULT 0,
    "compromised_assets" BIGINT DEFAULT 0,
    "active_sessions" BIGINT DEFAULT 0,
    "active_persistence" BIGINT DEFAULT 0,
    "total_commands_executed" BIGINT DEFAULT 0,
    "detection_risk_score" DOUBLE PRECISION DEFAULT 0.0,
    "objectives_complete" DOUBLE PRECISION DEFAULT 0.0,
    "evasion_success_pct" DOUBLE PRECISION DEFAULT 0.0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "campaign_objectives" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "objective" TEXT NOT NULL,
    "description" TEXT,
    "priority" BIGINT DEFAULT 1,
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_campaign_objectives_1" ON "campaign_objectives" ("campaign_id", "objective");
CREATE TABLE IF NOT EXISTS "campaign_phase_history" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "phase" TEXT NOT NULL,
    "timestamp" TEXT NOT NULL,
    "operator" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "campaign_reports" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "report_title" TEXT NOT NULL,
    "report_type" TEXT NOT NULL,
    "format" TEXT DEFAULT 'pdf',
    "generated_at" TEXT NOT NULL,
    "generated_by" TEXT NOT NULL,
    "file_path" TEXT,
    "file_hash" TEXT,
    "status" TEXT DEFAULT 'draft',
    "executive_summary" TEXT,
    "technical_summary" TEXT,
    "distribution_list" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_campaign_reports_1" ON "campaign_reports" ("campaign_id", "report_title", "generated_at");
CREATE TABLE IF NOT EXISTS "campaign_team_assignments" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    "assigned_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,
    "access_level" TEXT DEFAULT 'read_write',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_campaign_team_assignments_1" ON "campaign_team_assignments" ("campaign_id", "team_id");
CREATE TABLE IF NOT EXISTS "campaigns" (
    "id" BIGSERIAL,
    "name" TEXT NOT NULL,
    "project_id" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    "status" TEXT DEFAULT 'active',
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_campaigns_1" ON "campaigns" ("name");
CREATE TABLE IF NOT EXISTS "capability_assessment" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "capability_name" TEXT NOT NULL,
    "capability_type" TEXT NOT NULL,
    "difficulty_score" DOUBLE PRECISION DEFAULT 5.0,
    "success_rate" DOUBLE PRECISION DEFAULT 0.0,
    "defender_maturity_required" TEXT,
    "alternative_techniques" TEXT,
    "effectiveness_trend" TEXT DEFAULT 'stable',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "capability_timeline" (
    "id" BIGSERIAL,
    "capability_id" BIGINT NOT NULL,
    "execution_date" TEXT NOT NULL,
    "result" TEXT NOT NULL,
    "detection_likelihood" DOUBLE PRECISION DEFAULT 0.5,
    "remediation_difficulty" DOUBLE PRECISION DEFAULT 5.0,
    "notes" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "client_reports" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "client_name" TEXT NOT NULL,
    "report_title" TEXT NOT NULL,
    "report_date" TEXT NOT NULL,
    "generated_at" TEXT NOT NULL,
    "generated_by" TEXT NOT NULL,
    "filter_rules" TEXT,
    "include_exec_summary" BIGINT DEFAULT 1,
    "include_risk_dashboard" BIGINT DEFAULT 1,
    "include_metrics" BIGINT DEFAULT 1,
    "branding_logo_url" TEXT,
    "footer_text" TEXT,
    "status" TEXT DEFAULT 'draft',
    "file_path" TEXT,
    "file_hash" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "cognition_state_cache" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "snapshot_json" TEXT NOT NULL,
    "detection_pressure" DOUBLE PRECISION DEFAULT 0.0,
    "pressure_state" TEXT DEFAULT 'LOW',
    "infra_burn" TEXT DEFAULT 'fresh',
    "confidence_score" DOUBLE PRECISION DEFAULT 0.0,
    "updated_at" TEXT NOT NULL,
    "updated_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_cognition_state_cache_1" ON "cognition_state_cache" ("campaign_id");
CREATE TABLE IF NOT EXISTS "collaboration_sessions" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "session_name" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    "status" TEXT DEFAULT 'active',
    "max_operators" BIGINT DEFAULT 5,
    "sync_version" BIGINT DEFAULT 0,
    "last_sync" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "collaborative_changes" (
    "id" BIGSERIAL,
    "collab_session_id" BIGINT NOT NULL,
    "operator_id" BIGINT,
    "change_timestamp" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" BIGINT,
    "operation" TEXT,
    "old_value_hash" TEXT,
    "new_value_hash" TEXT,
    "conflict_detected" BIGINT DEFAULT 0,
    "resolved_by" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "command_execution_ledger" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "session_id" BIGINT DEFAULT NULL,
    "asset_id" BIGINT,
    "operator" TEXT NOT NULL,
    "executed_at" TEXT NOT NULL,
    "shell_type" TEXT,
    "command" TEXT NOT NULL,
    "output" TEXT DEFAULT NULL,
    "mitre_technique" TEXT,
    "success" BIGINT DEFAULT 1,
    "return_code" BIGINT DEFAULT NULL,
    "detection_likelihood" TEXT DEFAULT 'MEDIUM',
    "created_by" BIGINT,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_command_execution_ledger_1" ON "command_execution_ledger" ("campaign_id", "executed_at", "operator", "asset_id", "command");
CREATE TABLE IF NOT EXISTS "compliance_attestations" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "framework" TEXT NOT NULL,
    "attestation_date" TEXT NOT NULL,
    "attestor" TEXT NOT NULL,
    "total_requirements" BIGINT DEFAULT 0,
    "satisfied_requirements" BIGINT DEFAULT 0,
    "satisfaction_percent" DOUBLE PRECISION DEFAULT 0.0,
    "attestation_text" TEXT,
    "digital_signature" TEXT,
    "signed_at" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "compliance_frameworks" (
    "id" BIGSERIAL,
    "framework_name" TEXT NOT NULL,
    "description" TEXT,
    "requirements_count" BIGINT DEFAULT 0,
    "enabled" BIGINT DEFAULT 1,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_compliance_frameworks_1" ON "compliance_frameworks" ("framework_name");
CREATE TABLE IF NOT EXISTS "compliance_mappings" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "framework_id" BIGINT NOT NULL,
    "requirement_id" TEXT NOT NULL,
    "requirement_description" TEXT,
    "evidence_provided" TEXT,
    "status" TEXT DEFAULT 'pending',
    "last_verified" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_compliance_mappings_1" ON "compliance_mappings" ("campaign_id", "framework_id", "requirement_id");
CREATE TABLE IF NOT EXISTS "compliance_report_mappings" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "finding_id" BIGINT,
    "compliance_framework" TEXT NOT NULL,
    "requirement_id" TEXT NOT NULL,
    "requirement_name" TEXT,
    "finding_evidence_link" TEXT,
    "compliance_status" TEXT DEFAULT 'pending',
    "mapped_by" TEXT,
    "mapped_at" TEXT NOT NULL,
    "verified" BIGINT DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_compliance_report_mappings_1" ON "compliance_report_mappings" ("campaign_id", "compliance_framework", "requirement_id", "finding_id");
CREATE TABLE IF NOT EXISTS "coordination_logs" (
    "id" BIGSERIAL,
    "source_team_id" BIGINT NOT NULL,
    "target_team_id" BIGINT NOT NULL,
    "coordination_type" TEXT NOT NULL,
    "message" TEXT,
    "status" TEXT DEFAULT 'pending',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "resolved_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "credential_state" (
    "id" BIGSERIAL,
    "credential_id" BIGINT NOT NULL,
    "status" TEXT DEFAULT 'untested',
    "last_verified" TEXT DEFAULT NULL,
    "last_host" TEXT DEFAULT NULL,
    "failure_count" BIGINT DEFAULT 0,
    "success_count" BIGINT DEFAULT 0,
    "detection_risk" DOUBLE PRECISION DEFAULT 0.0,
    "burned_at" TEXT DEFAULT NULL,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_credential_state_1" ON "credential_state" ("credential_id");
CREATE TABLE IF NOT EXISTS "credentials" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "asset_id" BIGINT,
    "cred_type" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "secret" TEXT NOT NULL,
    "source" TEXT,
    "captured_by" BIGINT,
    "captured_at" TEXT,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "data_sharing_policies" (
    "id" BIGSERIAL,
    "source_team_id" BIGINT NOT NULL,
    "target_team_id" BIGINT NOT NULL,
    "resource_type" TEXT NOT NULL,
    "access_level" TEXT DEFAULT 'read_only',
    "requires_approval" BIGINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_data_sharing_policies_1" ON "data_sharing_policies" ("source_team_id", "target_team_id", "resource_type");
CREATE TABLE IF NOT EXISTS "defense_prediction" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "predicted_at" TEXT NOT NULL,
    "predicted_defense" TEXT NOT NULL,
    "confidence_score" DOUBLE PRECISION DEFAULT 0.5,
    "affected_techniques" TEXT,
    "mitigation_strategy" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "detection_events" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "asset_id" BIGINT,
    "detected_at" TEXT NOT NULL,
    "detection_type" TEXT NOT NULL,
    "indicator" TEXT NOT NULL,
    "source" TEXT,
    "confidence" DOUBLE PRECISION DEFAULT 0.5,
    "blue_team_aware" BIGINT DEFAULT 0,
    "response" TEXT DEFAULT NULL,
    "evasion_action" TEXT DEFAULT NULL,
    "mitigated" BIGINT DEFAULT 0,
    "logged_by" TEXT NOT NULL,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "detection_pressure_history" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "recorded_at" TEXT NOT NULL,
    "total_pressure" DOUBLE PRECISION DEFAULT 0.0,
    "pressure_state" TEXT DEFAULT 'LOW',
    "recent_alerts" BIGINT DEFAULT 0,
    "repetition_penalty" DOUBLE PRECISION DEFAULT 0.0,
    "failed_actions" BIGINT DEFAULT 0,
    "pressure_trend" TEXT DEFAULT 'stable',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "engagement_reports" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "report_title" TEXT NOT NULL,
    "report_date" TEXT NOT NULL,
    "generated_by" TEXT NOT NULL,
    "total_duration_hours" DOUBLE PRECISION DEFAULT 0.0,
    "total_assets_targeted" BIGINT DEFAULT 0,
    "assets_compromised" BIGINT DEFAULT 0,
    "credentials_obtained" BIGINT DEFAULT 0,
    "persistence_mechanisms" BIGINT DEFAULT 0,
    "total_detection_events" BIGINT DEFAULT 0,
    "detection_evasion_success_rate" DOUBLE PRECISION DEFAULT 0.0,
    "objectives_achieved" BIGINT DEFAULT 0,
    "techniques_executed" BIGINT,
    "report_summary" TEXT,
    "recommendations" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "enrichment_data" (
    "id" BIGSERIAL,
    "ioc_id" BIGINT NOT NULL,
    "enrichment_type" TEXT NOT NULL,
    "enrichment_value" TEXT NOT NULL,
    "source" TEXT,
    "confidence" DOUBLE PRECISION DEFAULT 0.5,
    "enriched_at" TEXT NOT NULL,
    "expires_at" TEXT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_enrichment_data_1" ON "enrichment_data" ("ioc_id", "enrichment_type");
CREATE TABLE IF NOT EXISTS "evasion_assessment" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "detection_event_id" BIGINT,
    "assessed_at" TEXT NOT NULL,
    "likely_detection_confidence" DOUBLE PRECISION DEFAULT 0.5,
    "recommended_action" TEXT,
    "executed_evasion" TEXT DEFAULT NULL,
    "result" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "evidence_items" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "finding_id" BIGINT,
    "artifact_type" TEXT NOT NULL,
    "description" TEXT,
    "sha256_hash" TEXT NOT NULL,
    "collected_by" BIGINT,
    "collection_method" TEXT,
    "collected_timestamp" TEXT NOT NULL,
    "source_host" TEXT,
    "technique_id" TEXT,
    "approval_status" TEXT DEFAULT 'pending',
    "approved_by" BIGINT,
    "approval_timestamp" TEXT DEFAULT '',
    "immutable" BIGINT DEFAULT 1,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_evidence_items_1" ON "evidence_items" ("sha256_hash");
CREATE TABLE IF NOT EXISTS "evidence_manifest_entries" (
    "id" BIGSERIAL,
    "manifest_id" BIGINT NOT NULL,
    "evidence_id" BIGINT,
    "artifact_type" TEXT NOT NULL,
    "artifact_hash" TEXT NOT NULL,
    "collection_method" TEXT,
    "collected_by" TEXT,
    "collected_at" TEXT NOT NULL,
    "size_bytes" BIGINT DEFAULT 0,
    "chain_of_custody" TEXT,
    "entry_hash" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_evidence_manifest_entries_1" ON "evidence_manifest_entries" ("manifest_id", "evidence_id", "artifact_hash");
CREATE TABLE IF NOT EXISTS "evidence_manifests" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "manifest_name" TEXT NOT NULL,
    "manifest_date" TEXT NOT NULL,
    "evidence_count" BIGINT DEFAULT 0,
    "total_size_bytes" BIGINT DEFAULT 0,
    "manifest_hash" TEXT NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "verified" BIGINT DEFAULT 0,
    "verified_at" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_evidence_manifests_2" ON "evidence_manifests" ("campaign_id", "manifest_name", "manifest_date");
CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_evidence_manifests_1" ON "evidence_manifests" ("manifest_hash");
CREATE TABLE IF NOT EXISTS "finding_summaries" (
    "id" BIGSERIAL,
    "finding_id" BIGINT NOT NULL,
    "summary_text" TEXT NOT NULL,
    "impact_assessment" TEXT,
    "remediation_steps" TEXT,
    "priority_level" TEXT DEFAULT 'MEDIUM',
    "cvss_31_vector" TEXT,
    "cvss_31_score" DOUBLE PRECISION DEFAULT 0.0,
    "severity_rating" TEXT,
    "affected_assets" TEXT,
    "evidence_links" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_finding_summaries_1" ON "finding_summaries" ("finding_id");
CREATE TABLE IF NOT EXISTS "findings" (
    "id" BIGSERIAL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "cvss_score" DOUBLE PRECISION DEFAULT 0.0,
    "mitre_id" TEXT DEFAULT '',
    "tactic_id" TEXT DEFAULT '',
    "status" TEXT DEFAULT 'Open',
    "evidence" TEXT DEFAULT '',
    "remediation" TEXT DEFAULT '',
    "project_id" TEXT DEFAULT 'DEFAULT',
    "cvss_vector" TEXT DEFAULT '',
    "evidence_hash" TEXT DEFAULT '',
    "created_by" BIGINT DEFAULT NULL,
    "last_modified_by" BIGINT DEFAULT NULL,
    "assigned_to" BIGINT DEFAULT NULL,
    "visibility" TEXT DEFAULT 'group',
    "tags" TEXT DEFAULT '',
    "approval_status" TEXT DEFAULT 'pending',
    "approved_by" BIGINT DEFAULT NULL,
    "approval_timestamp" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "groups" (
    "id" BIGSERIAL,
    "name" TEXT NOT NULL,
    "description" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_groups_1" ON "groups" ("name");
CREATE TABLE IF NOT EXISTS "immutable_audit_log" (
    "id" BIGSERIAL,
    "log_entry_id" TEXT NOT NULL,
    "previous_hash" TEXT,
    "log_data" TEXT NOT NULL,
    "log_hash" TEXT NOT NULL,
    "timestamp" TEXT NOT NULL,
    "actor" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "signature" TEXT,
    "verified" BIGINT DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_immutable_audit_log_1" ON "immutable_audit_log" ("log_entry_id");
CREATE TABLE IF NOT EXISTS "indicators_of_compromise" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "indicator_type" TEXT NOT NULL,
    "indicator_value" TEXT NOT NULL,
    "source_feed_id" BIGINT,
    "threat_level" TEXT DEFAULT 'MEDIUM',
    "threat_actor_id" BIGINT,
    "first_seen" TEXT NOT NULL,
    "last_seen" TEXT,
    "matched_count" BIGINT DEFAULT 0,
    "confidence" DOUBLE PRECISION DEFAULT 0.5,
    "classification" TEXT DEFAULT 'UNKNOWN',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_indicators_of_compromise_1" ON "indicators_of_compromise" ("campaign_id", "indicator_type", "indicator_value");
CREATE TABLE IF NOT EXISTS "intel_indicators" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "feed_id" BIGINT,
    "indicator_type" TEXT NOT NULL,
    "indicator_value" TEXT NOT NULL,
    "threat_level" TEXT DEFAULT 'MEDIUM',
    "matched_at" TEXT,
    "correlation" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "intelligence_archive" (
    "id" BIGSERIAL,
    "actor_id" BIGINT,
    "campaign_id" BIGINT,
    "archive_type" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "tags" TEXT,
    "classification" TEXT DEFAULT 'UNCLASSIFIED',
    "source" TEXT,
    "archived_at" TEXT NOT NULL,
    "archived_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_intelligence_archive_1" ON "intelligence_archive" ("actor_id", "archive_type", "campaign_id");
CREATE TABLE IF NOT EXISTS "loot" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "asset_id" BIGINT,
    "path" TEXT,
    "description" TEXT,
    "classification" TEXT,
    "hash" TEXT,
    "stored_at" TEXT,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "meta" (
    "key" TEXT,
    "value" TEXT,
    PRIMARY KEY ("key")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_meta_1" ON "meta" ("key");
CREATE TABLE IF NOT EXISTS "objective_progress" (
    "id" BIGSERIAL,
    "objective_id" BIGINT NOT NULL,
    "action_id" TEXT NOT NULL,
    "finding_id" TEXT DEFAULT NULL,
    "progress_pct" DOUBLE PRECISION DEFAULT 0.0,
    "status" TEXT DEFAULT 'in_progress',
    "completed_at" TEXT DEFAULT NULL,
    "completed_by" TEXT DEFAULT NULL,
    "evidence" TEXT,
    "notes" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_objective_progress_1" ON "objective_progress" ("objective_id", "action_id");
CREATE TABLE IF NOT EXISTS "operation_phases" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "phase" TEXT NOT NULL,
    "entered_at" TEXT NOT NULL,
    "exited_at" TEXT DEFAULT NULL,
    "entered_by" BIGINT,
    "notes" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_operation_phases_1" ON "operation_phases" ("campaign_id", "entered_at");
CREATE TABLE IF NOT EXISTS "operator_performance" (
    "id" BIGSERIAL,
    "user_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    "period_start" TIMESTAMP NOT NULL,
    "period_end" TIMESTAMP NOT NULL,
    "findings_created" BIGINT DEFAULT 0,
    "findings_approved" BIGINT DEFAULT 0,
    "approval_rate" DOUBLE PRECISION DEFAULT 0.0,
    "average_cvss_score" DOUBLE PRECISION DEFAULT 0.0,
    "total_operations" BIGINT DEFAULT 0,
    "success_rate" DOUBLE PRECISION DEFAULT 0.0,
    "effectiveness_score" DOUBLE PRECISION DEFAULT 0.0,
    "calculated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_operator_performance_1" ON "operator_performance" ("user_id", "team_id", "period_start", "period_end");
CREATE TABLE IF NOT EXISTS "operator_presence" (
    "id" BIGSERIAL,
    "collab_session_id" BIGINT NOT NULL,
    "operator_id" BIGINT NOT NULL,
    "joined_at" TEXT NOT NULL,
    "last_heartbeat" TEXT NOT NULL,
    "cursor_position" TEXT,
    "viewing_asset" BIGINT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "operator_tempo_metrics" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "operator_id" BIGINT,
    "recorded_at" TEXT NOT NULL,
    "actions_per_hour" DOUBLE PRECISION DEFAULT 0.0,
    "action_intensity" TEXT DEFAULT 'normal',
    "spike_detected" BIGINT DEFAULT 0,
    "suggested_slow_window" TEXT DEFAULT '',
    "staging_recommendation" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "opsec_rules" (
    "id" BIGSERIAL,
    "technique" TEXT NOT NULL,
    "target_tag" TEXT NOT NULL,
    "time_window" TEXT NOT NULL,
    "risk_score" DOUBLE PRECISION NOT NULL,
    "reason" TEXT NOT NULL,
    "created_by" BIGINT,
    "created_at" TEXT NOT NULL,
    "active" BIGINT DEFAULT 1,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_opsec_rules_1" ON "opsec_rules" ("technique", "target_tag", "time_window");
CREATE TABLE IF NOT EXISTS "persistence_registry" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "asset_id" BIGINT,
    "persistence_type" TEXT NOT NULL,
    "mechanism_details" TEXT NOT NULL,
    "installed_at" TEXT NOT NULL,
    "installed_by" TEXT NOT NULL,
    "status" TEXT DEFAULT 'active',
    "last_verified" TEXT DEFAULT NULL,
    "verification_result" TEXT DEFAULT NULL,
    "cleanup_required" BIGINT DEFAULT 0,
    "redundancy_group" TEXT,
    "backup_persistence_id" BIGINT DEFAULT NULL,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_persistence_registry_1" ON "persistence_registry" ("campaign_id", "asset_id", "persistence_type", "mechanism_details");
CREATE TABLE IF NOT EXISTS "persistence_verification_log" (
    "id" BIGSERIAL,
    "persistence_id" BIGINT NOT NULL,
    "verified_at" TEXT NOT NULL,
    "verified_by" TEXT NOT NULL,
    "result" TEXT NOT NULL,
    "evidence" TEXT,
    "remediation_needed" BIGINT DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "projects" (
    "id" BIGSERIAL,
    "name" TEXT NOT NULL,
    "description" TEXT DEFAULT '',
    "group_id" BIGINT,
    "archived" BIGINT DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_projects_1" ON "projects" ("name");
CREATE TABLE IF NOT EXISTS "purge_operations" (
    "id" BIGSERIAL,
    "purge_timestamp" TEXT NOT NULL,
    "policy_id" BIGINT,
    "records_deleted" BIGINT DEFAULT 0,
    "records_archived" BIGINT DEFAULT 0,
    "executed_by" TEXT NOT NULL,
    "completion_status" TEXT DEFAULT 'pending',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "re_authentication_log" (
    "id" BIGSERIAL,
    "user_id" BIGINT NOT NULL,
    "re_auth_timestamp" TEXT NOT NULL,
    "reason" TEXT,
    "success" BIGINT DEFAULT 1,
    "method" TEXT DEFAULT 'PASSPHRASE',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "real_time_alerts" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "alert_timestamp" TEXT NOT NULL,
    "alert_type" TEXT NOT NULL,
    "severity" TEXT DEFAULT 'INFO',
    "message" TEXT NOT NULL,
    "related_asset" BIGINT,
    "acknowledged" BIGINT DEFAULT 0,
    "acknowledged_by" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "recommendation_history" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "opportunity_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "technique" TEXT DEFAULT '',
    "target_asset" TEXT DEFAULT '',
    "score" DOUBLE PRECISION DEFAULT 0.0,
    "stealth" DOUBLE PRECISION DEFAULT 0.0,
    "value" DOUBLE PRECISION DEFAULT 0.0,
    "risk" DOUBLE PRECISION DEFAULT 0.0,
    "confidence" DOUBLE PRECISION DEFAULT 0.0,
    "explanation" TEXT DEFAULT '',
    "safer_alternative" TEXT DEFAULT '',
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "relations" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "src_type" TEXT,
    "src_id" BIGINT,
    "rel_type" TEXT,
    "dst_type" TEXT,
    "dst_id" BIGINT,
    "integrity_hash" TEXT DEFAULT '',
    "confidence" DOUBLE PRECISION DEFAULT 1.0,
    "evidence_id" BIGINT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "relationships" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "source_type" TEXT NOT NULL,
    "source_id" TEXT NOT NULL,
    "relation" TEXT NOT NULL,
    "target_type" TEXT NOT NULL,
    "target_id" TEXT NOT NULL,
    "confidence" DOUBLE PRECISION DEFAULT 1.0,
    "evidence_id" TEXT DEFAULT NULL,
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_relationships_1" ON "relationships" ("campaign_id", "source_type", "source_id", "relation", "target_type", "target_id");
CREATE TABLE IF NOT EXISTS "remediation_actions" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "asset_id" BIGINT,
    "action_description" TEXT NOT NULL,
    "action_timestamp" TEXT NOT NULL,
    "initiated_by" TEXT NOT NULL,
    "status" TEXT DEFAULT 'in_progress',
    "effectiveness" DOUBLE PRECISION DEFAULT 0.0,
    "blocked_techniques" TEXT,
    "evidence" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "remediation_impact" (
    "id" BIGSERIAL,
    "remediation_id" BIGINT NOT NULL,
    "affected_persistence_mechanisms" BIGINT DEFAULT 0,
    "affected_sessions" BIGINT DEFAULT 0,
    "affected_access_paths" BIGINT DEFAULT 0,
    "impact_score" DOUBLE PRECISION DEFAULT 0.0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "replay_events" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "event_type" TEXT NOT NULL,
    "event_time" TEXT NOT NULL,
    "operator" TEXT DEFAULT 'SYSTEM',
    "asset_id" BIGINT,
    "technique" TEXT DEFAULT '',
    "success" BIGINT DEFAULT 1,
    "summary" TEXT DEFAULT '',
    "details_json" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "report_history" (
    "id" BIGSERIAL,
    "report_schedule_id" BIGINT NOT NULL,
    "generation_timestamp" TEXT NOT NULL,
    "file_path" TEXT,
    "file_size" BIGINT DEFAULT 0,
    "generation_status" TEXT DEFAULT 'success',
    "error_message" TEXT DEFAULT NULL,
    "recipients" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "report_schedules" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "report_name" TEXT NOT NULL,
    "report_type" TEXT NOT NULL,
    "frequency" TEXT NOT NULL,
    "next_generation" TEXT NOT NULL,
    "last_generated" TEXT DEFAULT NULL,
    "email_recipients" TEXT,
    "enabled" BIGINT DEFAULT 1,
    "created_by" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_report_schedules_1" ON "report_schedules" ("campaign_id", "report_name");
CREATE TABLE IF NOT EXISTS "report_templates" (
    "id" BIGSERIAL,
    "template_name" TEXT NOT NULL,
    "template_type" TEXT NOT NULL,
    "format" TEXT DEFAULT 'jinja2',
    "content" TEXT NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "description" TEXT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_report_templates_1" ON "report_templates" ("template_name");
CREATE TABLE IF NOT EXISTS "report_versions" (
    "id" BIGSERIAL,
    "report_id" BIGINT NOT NULL,
    "version_number" BIGINT DEFAULT 1,
    "version_date" TEXT NOT NULL,
    "changes" TEXT,
    "approved_by" TEXT,
    "approved_at" TEXT,
    "distribution_count" BIGINT DEFAULT 0,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "retention_policies" (
    "id" BIGSERIAL,
    "policy_name" TEXT NOT NULL,
    "data_type" TEXT NOT NULL,
    "retention_days" BIGINT DEFAULT 90,
    "action_on_expiry" TEXT DEFAULT 'archive',
    "created_at" TEXT NOT NULL,
    "enabled" BIGINT DEFAULT 1,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_retention_policies_1" ON "retention_policies" ("policy_name");
CREATE TABLE IF NOT EXISTS "risk_scores" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "finding_id" BIGINT,
    "risk_level" TEXT DEFAULT 'MEDIUM',
    "threat_score" DOUBLE PRECISION DEFAULT 5.0,
    "likelihood_score" DOUBLE PRECISION DEFAULT 5.0,
    "impact_score" DOUBLE PRECISION DEFAULT 5.0,
    "final_score" DOUBLE PRECISION DEFAULT 5.0,
    "trend" TEXT DEFAULT 'stable',
    "calculated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "scheduled_tasks" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "task_template_id" BIGINT,
    "scheduled_at" TEXT NOT NULL,
    "trigger_condition" TEXT,
    "priority" BIGINT DEFAULT 1,
    "max_retries" BIGINT DEFAULT 3,
    "status" TEXT DEFAULT 'pending',
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "secure_deletion_log" (
    "id" BIGSERIAL,
    "deletion_timestamp" TEXT NOT NULL,
    "data_type" TEXT NOT NULL,
    "record_count" BIGINT,
    "deletion_method" TEXT DEFAULT 'multi-pass-overwrite',
    "verification_hash" TEXT,
    "verified" BIGINT DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "sensitive_field_audit" (
    "id" BIGSERIAL,
    "field_name" TEXT NOT NULL,
    "accessed_by" BIGINT,
    "accessed_at" TEXT NOT NULL,
    "access_type" TEXT NOT NULL,
    "tlp_level" TEXT,
    "ip_address" TEXT,
    "session_id" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "session_lifecycle" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "asset_id" BIGINT,
    "session_identifier" TEXT NOT NULL,
    "session_type" TEXT NOT NULL,
    "opened_by" TEXT NOT NULL,
    "opened_at" TEXT NOT NULL,
    "closed_at" TEXT DEFAULT NULL,
    "detected_at" TEXT DEFAULT NULL,
    "is_active" BIGINT DEFAULT 1,
    "activation_count" BIGINT DEFAULT 1,
    "revived_at" TEXT DEFAULT NULL,
    "persistence_mechanism" TEXT,
    "backup_session_id" BIGINT DEFAULT NULL,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_session_lifecycle_1" ON "session_lifecycle" ("campaign_id", "asset_id", "session_identifier");
CREATE TABLE IF NOT EXISTS "session_management" (
    "id" BIGSERIAL,
    "user_id" BIGINT NOT NULL,
    "session_token" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "last_activity" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "timeout_minutes" BIGINT DEFAULT 120,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "is_active" BIGINT DEFAULT 1,
    "closed_at" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_session_management_1" ON "session_management" ("session_token");
CREATE TABLE IF NOT EXISTS "sessions" (
    "id" BIGSERIAL,
    "user_id" BIGINT NOT NULL,
    "session_token" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_sessions_1" ON "sessions" ("session_token");
CREATE TABLE IF NOT EXISTS "sessions_ops" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT,
    "asset_id" BIGINT,
    "session_type" TEXT,
    "user" TEXT,
    "pid" BIGINT,
    "tunnel" TEXT,
    "status" TEXT,
    "opened_at" TEXT,
    "closed_at" TEXT,
    "integrity_hash" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "target_lock_diffs" (
    "id" BIGSERIAL,
    "lock_id" BIGINT,
    "before_hash" TEXT NOT NULL,
    "after_hash" TEXT NOT NULL,
    "diff_json" TEXT NOT NULL,
    "reviewed_by" BIGINT,
    "reviewed_at" TEXT DEFAULT NULL,
    "approved" BIGINT DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "target_locks" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "target_type" TEXT NOT NULL,
    "target_id" TEXT NOT NULL,
    "operator_id" BIGINT NOT NULL,
    "locked_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "context_json" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_target_locks_1" ON "target_locks" ("campaign_id", "target_type", "target_id");
CREATE TABLE IF NOT EXISTS "task_execution_log" (
    "id" BIGSERIAL,
    "scheduled_task_id" BIGINT NOT NULL,
    "execution_start" TEXT NOT NULL,
    "execution_end" TEXT,
    "status" TEXT NOT NULL,
    "result" TEXT,
    "error_message" TEXT DEFAULT NULL,
    "output_log" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "task_templates" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "template_name" TEXT NOT NULL,
    "description" TEXT,
    "created_by" BIGINT,
    "created_at" TEXT NOT NULL,
    "task_chain" TEXT NOT NULL,
    "enabled" BIGINT DEFAULT 1,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_task_templates_1" ON "task_templates" ("campaign_id", "template_name");
CREATE TABLE IF NOT EXISTS "team_intelligence_pools" (
    "id" BIGSERIAL,
    "team_id" BIGINT NOT NULL,
    "pool_name" TEXT NOT NULL,
    "description" TEXT,
    "intelligence_items" TEXT,
    "is_shared" BIGINT DEFAULT 0,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_team_intelligence_pools_1" ON "team_intelligence_pools" ("team_id", "pool_name");
CREATE TABLE IF NOT EXISTS "team_members" (
    "id" BIGSERIAL,
    "team_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "team_role" TEXT DEFAULT 'member',
    "joined_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_team_members_1" ON "team_members" ("team_id", "user_id");
CREATE TABLE IF NOT EXISTS "team_metrics" (
    "id" BIGSERIAL,
    "team_id" BIGINT NOT NULL,
    "period_start" TIMESTAMP NOT NULL,
    "period_end" TIMESTAMP NOT NULL,
    "total_findings" BIGINT DEFAULT 0,
    "critical_findings" BIGINT DEFAULT 0,
    "approved_findings" BIGINT DEFAULT 0,
    "average_approval_time_hours" DOUBLE PRECISION DEFAULT 0.0,
    "total_campaigns" BIGINT DEFAULT 0,
    "active_campaigns" BIGINT DEFAULT 0,
    "calculated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_team_metrics_1" ON "team_metrics" ("team_id", "period_start", "period_end");
CREATE TABLE IF NOT EXISTS "team_permissions" (
    "id" BIGSERIAL,
    "team_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "permission_type" TEXT NOT NULL,
    "resource_type" TEXT,
    "granted_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "granted_by" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_team_permissions_1" ON "team_permissions" ("team_id", "user_id", "permission_type", "resource_type");
CREATE TABLE IF NOT EXISTS "team_roles" (
    "id" BIGSERIAL,
    "team_id" BIGINT NOT NULL,
    "role_name" TEXT NOT NULL,
    "permissions" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_team_roles_1" ON "team_roles" ("team_id", "role_name");
CREATE TABLE IF NOT EXISTS "teams" (
    "id" BIGSERIAL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "lead_operator_id" BIGINT NOT NULL,
    "budget_usd" DOUBLE PRECISION DEFAULT 0.0,
    "status" TEXT DEFAULT 'active',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_teams_1" ON "teams" ("name");
CREATE TABLE IF NOT EXISTS "technique_patterns" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "technique" TEXT NOT NULL,
    "asset_type" TEXT DEFAULT 'unknown',
    "executions" BIGINT DEFAULT 0,
    "successes" BIGINT DEFAULT 0,
    "failures" BIGINT DEFAULT 0,
    "avg_time_to_compromise" DOUBLE PRECISION DEFAULT 0.0,
    "last_seen" TEXT NOT NULL,
    "confidence" DOUBLE PRECISION DEFAULT 0.5,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_technique_patterns_1" ON "technique_patterns" ("campaign_id", "technique", "asset_type");
CREATE TABLE IF NOT EXISTS "threat_actors" (
    "id" BIGSERIAL,
    "actor_name" TEXT NOT NULL,
    "aliases" TEXT,
    "origin_country" TEXT,
    "organization" TEXT,
    "known_targets" TEXT,
    "first_seen" TEXT,
    "last_seen" TEXT,
    "attribution_confidence" DOUBLE PRECISION DEFAULT 0.5,
    "description" TEXT,
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_threat_actors_1" ON "threat_actors" ("actor_name");
CREATE TABLE IF NOT EXISTS "threat_correlations" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "correlation_type" TEXT NOT NULL,
    "source_type" TEXT NOT NULL,
    "source_id" BIGINT,
    "target_type" TEXT NOT NULL,
    "target_id" BIGINT,
    "confidence" DOUBLE PRECISION DEFAULT 0.5,
    "evidence" TEXT,
    "correlation_timestamp" TEXT NOT NULL,
    "correlated_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_threat_correlations_1" ON "threat_correlations" ("campaign_id", "source_type", "source_id", "target_type", "target_id");
CREATE TABLE IF NOT EXISTS "threat_feeds" (
    "id" BIGSERIAL,
    "feed_name" TEXT NOT NULL,
    "feed_type" TEXT NOT NULL,
    "feed_url" TEXT,
    "api_key_hash" TEXT,
    "last_updated" TEXT,
    "last_error" TEXT,
    "status" TEXT DEFAULT 'active',
    "description" TEXT,
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    "feed_icon" TEXT DEFAULT '🔗',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_threat_feeds_1" ON "threat_feeds" ("feed_name");
CREATE TABLE IF NOT EXISTS "threat_intelligence_feeds" (
    "id" BIGSERIAL,
    "feed_name" TEXT NOT NULL,
    "feed_type" TEXT NOT NULL,
    "feed_url" TEXT,
    "last_updated" TEXT,
    "status" TEXT DEFAULT 'active',
    "description" TEXT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_threat_intelligence_feeds_1" ON "threat_intelligence_feeds" ("feed_name");
CREATE TABLE IF NOT EXISTS "tlp_classifications" (
    "id" BIGSERIAL,
    "data_id" TEXT NOT NULL,
    "data_type" TEXT NOT NULL,
    "tlp_level" TEXT NOT NULL,
    "encrypted" BIGINT DEFAULT 1,
    "encryption_algorithm" TEXT DEFAULT 'AES-256-GCM',
    "iv_hash" TEXT,
    "created_at" TEXT NOT NULL,
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_tlp_classifications_1" ON "tlp_classifications" ("data_id", "data_type");
CREATE TABLE IF NOT EXISTS "ttp_execution_metrics" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "mitre_technique" TEXT NOT NULL,
    "times_executed" BIGINT DEFAULT 1,
    "success_rate" DOUBLE PRECISION DEFAULT 1.0,
    "avg_detection_likelihood" DOUBLE PRECISION DEFAULT 0.5,
    "effectiveness_score" DOUBLE PRECISION DEFAULT 0.0,
    "last_executed" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_capabilities" (
    "user_id" BIGINT,
    "capability_profile" TEXT NOT NULL DEFAULT 'operator-core',
    "updated_at" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    PRIMARY KEY ("user_id")
);

CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGSERIAL,
    "username" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "salt" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'operator',
    "group_id" BIGINT,
    "created_at" TEXT NOT NULL,
    "last_login" TEXT DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_users_1" ON "users" ("username");
CREATE TABLE IF NOT EXISTS "webhook_delivery_log" (
    "id" BIGSERIAL,
    "webhook_id" BIGINT NOT NULL,
    "delivery_timestamp" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "payload_hash" TEXT,
    "http_status" BIGINT,
    "retry_count" BIGINT DEFAULT 0,
    "delivered" BIGINT DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "webhook_subscriptions" (
    "id" BIGSERIAL,
    "campaign_id" BIGINT NOT NULL,
    "webhook_url" TEXT NOT NULL,
    "webhook_type" TEXT NOT NULL,
    "events" TEXT NOT NULL,
    "secret_key" TEXT,
    "active" BIGINT DEFAULT 1,
    "created_at" TEXT NOT NULL,
    "last_triggered" TEXT DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_webhook_subscriptions_1" ON "webhook_subscriptions" ("campaign_id", "webhook_url");
CREATE INDEX IF NOT EXISTS idx_actor_ttps_actor ON actor_ttps(actor_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_detections_campaign ON anomaly_detections(campaign_id);
CREATE INDEX IF NOT EXISTS idx_api_integrations_campaign ON api_integrations(campaign_id);
CREATE INDEX IF NOT EXISTS idx_audit_certification_reports_campaign ON audit_certification_reports(campaign_id);
CREATE INDEX IF NOT EXISTS idx_audit_verification_chain_log ON audit_verification_chain(audit_log_id);
CREATE INDEX IF NOT EXISTS idx_behavioral_profiles_campaign ON behavioral_profiles(campaign_id);
CREATE INDEX IF NOT EXISTS idx_c2_infrastructure_campaign ON c2_infrastructure(campaign_id, node_name);
CREATE INDEX IF NOT EXISTS idx_camp_team_camp ON campaign_team_assignments(campaign_id);
CREATE INDEX IF NOT EXISTS idx_camp_team_team ON campaign_team_assignments(team_id);
CREATE INDEX IF NOT EXISTS idx_campaign_metrics_campaign ON campaign_metrics(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_metrics_time ON campaign_metrics(metric_timestamp);
CREATE INDEX IF NOT EXISTS idx_campaign_objectives_campaign ON campaign_objectives(campaign_id);
CREATE INDEX IF NOT EXISTS idx_capability_assessment_campaign ON capability_assessment(campaign_id);
CREATE INDEX IF NOT EXISTS idx_capability_timeline_capability ON capability_timeline(capability_id);
CREATE INDEX IF NOT EXISTS idx_client_reports_campaign ON client_reports(campaign_id);
CREATE INDEX IF NOT EXISTS idx_client_reports_client ON client_reports(client_name);
CREATE INDEX IF NOT EXISTS idx_client_reports_date ON client_reports(report_date);
CREATE INDEX IF NOT EXISTS idx_cognition_state_cache_campaign ON cognition_state_cache(campaign_id);
CREATE INDEX IF NOT EXISTS idx_collaboration_sessions_campaign ON collaboration_sessions(campaign_id);
CREATE INDEX IF NOT EXISTS idx_collaborative_changes_session ON collaborative_changes(collab_session_id);
CREATE INDEX IF NOT EXISTS idx_command_ledger_asset ON command_execution_ledger(campaign_id, asset_id);
CREATE INDEX IF NOT EXISTS idx_command_ledger_campaign ON command_execution_ledger(campaign_id);
CREATE INDEX IF NOT EXISTS idx_command_ledger_time ON command_execution_ledger(executed_at);
CREATE INDEX IF NOT EXISTS idx_compliance_attestations_campaign ON compliance_attestations(campaign_id);
CREATE INDEX IF NOT EXISTS idx_compliance_attestations_framework ON compliance_attestations(framework);
CREATE INDEX IF NOT EXISTS idx_compliance_mappings_campaign ON compliance_mappings(campaign_id);
CREATE INDEX IF NOT EXISTS idx_compliance_report_mappings_campaign ON compliance_report_mappings(campaign_id);
CREATE INDEX IF NOT EXISTS idx_compliance_report_mappings_framework ON compliance_report_mappings(compliance_framework);
CREATE INDEX IF NOT EXISTS idx_coord_source ON coordination_logs(source_team_id);
CREATE INDEX IF NOT EXISTS idx_coord_status ON coordination_logs(status);
CREATE INDEX IF NOT EXISTS idx_coord_target ON coordination_logs(target_team_id);
CREATE INDEX IF NOT EXISTS idx_credential_state_status ON credential_state(status);
CREATE INDEX IF NOT EXISTS idx_defense_prediction_campaign ON defense_prediction(campaign_id);
CREATE INDEX IF NOT EXISTS idx_detection_events_campaign ON detection_events(campaign_id);
CREATE INDEX IF NOT EXISTS idx_detection_events_time ON detection_events(detected_at);
CREATE INDEX IF NOT EXISTS idx_detection_pressure_history_campaign ON detection_pressure_history(campaign_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_engagement_reports_campaign ON engagement_reports(campaign_id);
CREATE INDEX IF NOT EXISTS idx_enrichment_ioc ON enrichment_data(ioc_id);
CREATE INDEX IF NOT EXISTS idx_evasion_assessment_campaign ON evasion_assessment(campaign_id);
CREATE INDEX IF NOT EXISTS idx_evidence_manifest_entries_manifest ON evidence_manifest_entries(manifest_id);
CREATE INDEX IF NOT EXISTS idx_evidence_manifests_campaign ON evidence_manifests(campaign_id);
CREATE INDEX IF NOT EXISTS idx_evidence_manifests_date ON evidence_manifests(manifest_date);
CREATE INDEX IF NOT EXISTS idx_finding_summaries_finding ON finding_summaries(finding_id);
CREATE INDEX IF NOT EXISTS idx_finding_summaries_priority ON finding_summaries(priority_level);
CREATE INDEX IF NOT EXISTS idx_immutable_audit_log_timestamp ON immutable_audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_intel_indicators_campaign ON intel_indicators(campaign_id);
CREATE INDEX IF NOT EXISTS idx_intel_indicators_type ON intel_indicators(indicator_type);
CREATE INDEX IF NOT EXISTS idx_intel_pool_team ON team_intelligence_pools(team_id);
CREATE INDEX IF NOT EXISTS idx_intelligence_archive_actor ON intelligence_archive(actor_id);
CREATE INDEX IF NOT EXISTS idx_ioc_campaign ON indicators_of_compromise(campaign_id);
CREATE INDEX IF NOT EXISTS idx_ioc_type ON indicators_of_compromise(indicator_type);
CREATE INDEX IF NOT EXISTS idx_objective_progress_objective ON objective_progress(objective_id);
CREATE INDEX IF NOT EXISTS idx_operation_phases_campaign ON operation_phases(campaign_id);
CREATE INDEX IF NOT EXISTS idx_operation_phases_entered ON operation_phases(entered_at);
CREATE INDEX IF NOT EXISTS idx_operator_presence_session ON operator_presence(collab_session_id);
CREATE INDEX IF NOT EXISTS idx_operator_tempo_metrics_campaign ON operator_tempo_metrics(campaign_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_perf_period ON operator_performance(period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_perf_team ON operator_performance(team_id);
CREATE INDEX IF NOT EXISTS idx_perf_user ON operator_performance(user_id);
CREATE INDEX IF NOT EXISTS idx_persistence_registry_asset ON persistence_registry(campaign_id, asset_id);
CREATE INDEX IF NOT EXISTS idx_persistence_registry_campaign ON persistence_registry(campaign_id);
CREATE INDEX IF NOT EXISTS idx_persistence_registry_status ON persistence_registry(status);
CREATE INDEX IF NOT EXISTS idx_persistence_verification_log_persistence ON persistence_verification_log(persistence_id);
CREATE INDEX IF NOT EXISTS idx_purge_operations_timestamp ON purge_operations(purge_timestamp);
CREATE INDEX IF NOT EXISTS idx_real_time_alerts_campaign ON real_time_alerts(campaign_id);
CREATE INDEX IF NOT EXISTS idx_real_time_alerts_severity ON real_time_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_recommendation_history_campaign ON recommendation_history(campaign_id, created_at);
CREATE INDEX IF NOT EXISTS idx_relationships_campaign ON relationships(campaign_id);
CREATE INDEX IF NOT EXISTS idx_relationships_source ON relationships(campaign_id, source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_relationships_target ON relationships(campaign_id, target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_remediation_actions_campaign ON remediation_actions(campaign_id);
CREATE INDEX IF NOT EXISTS idx_remediation_actions_status ON remediation_actions(status);
CREATE INDEX IF NOT EXISTS idx_remediation_impact_remediation ON remediation_impact(remediation_id);
CREATE INDEX IF NOT EXISTS idx_replay_events_campaign ON replay_events(campaign_id, event_time);
CREATE INDEX IF NOT EXISTS idx_report_history_schedule ON report_history(report_schedule_id);
CREATE INDEX IF NOT EXISTS idx_report_history_timestamp ON report_history(generation_timestamp);
CREATE INDEX IF NOT EXISTS idx_report_schedules_campaign ON report_schedules(campaign_id);
CREATE INDEX IF NOT EXISTS idx_report_schedules_next ON report_schedules(next_generation);
CREATE INDEX IF NOT EXISTS idx_report_templates_type ON report_templates(template_type);
CREATE INDEX IF NOT EXISTS idx_report_versions_approved ON report_versions(approved_at);
CREATE INDEX IF NOT EXISTS idx_report_versions_report ON report_versions(report_id);
CREATE INDEX IF NOT EXISTS idx_retention_policies_type ON retention_policies(data_type);
CREATE INDEX IF NOT EXISTS idx_risk_scores_campaign ON risk_scores(campaign_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_campaign ON scheduled_tasks(campaign_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_status ON scheduled_tasks(status);
CREATE INDEX IF NOT EXISTS idx_secure_deletion_log_timestamp ON secure_deletion_log(deletion_timestamp);
CREATE INDEX IF NOT EXISTS idx_sensitive_field_audit_time ON sensitive_field_audit(accessed_at);
CREATE INDEX IF NOT EXISTS idx_session_lifecycle_active ON session_lifecycle(campaign_id, is_active);
CREATE INDEX IF NOT EXISTS idx_session_lifecycle_asset ON session_lifecycle(asset_id);
CREATE INDEX IF NOT EXISTS idx_session_lifecycle_campaign ON session_lifecycle(campaign_id);
CREATE INDEX IF NOT EXISTS idx_session_management_active ON session_management(is_active);
CREATE INDEX IF NOT EXISTS idx_session_management_expires ON session_management(expires_at);
CREATE INDEX IF NOT EXISTS idx_session_management_user ON session_management(user_id);
CREATE INDEX IF NOT EXISTS idx_sharing_source ON data_sharing_policies(source_team_id);
CREATE INDEX IF NOT EXISTS idx_sharing_target ON data_sharing_policies(target_team_id);
CREATE INDEX IF NOT EXISTS idx_target_locks_campaign ON target_locks(campaign_id);
CREATE INDEX IF NOT EXISTS idx_target_locks_expires ON target_locks(expires_at);
CREATE INDEX IF NOT EXISTS idx_target_locks_target ON target_locks(campaign_id, target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_task_execution_log_task ON task_execution_log(scheduled_task_id);
CREATE INDEX IF NOT EXISTS idx_task_templates_campaign ON task_templates(campaign_id);
CREATE INDEX IF NOT EXISTS idx_team_members_team ON team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_team_members_user ON team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_team_metrics_period ON team_metrics(period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_team_metrics_team ON team_metrics(team_id);
CREATE INDEX IF NOT EXISTS idx_team_perms_team ON team_permissions(team_id);
CREATE INDEX IF NOT EXISTS idx_team_perms_user ON team_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_team_roles_team ON team_roles(team_id);
CREATE INDEX IF NOT EXISTS idx_teams_lead ON teams(lead_operator_id);
CREATE INDEX IF NOT EXISTS idx_technique_patterns_campaign ON technique_patterns(campaign_id, technique);
CREATE INDEX IF NOT EXISTS idx_threat_actors_name ON threat_actors(actor_name);
CREATE INDEX IF NOT EXISTS idx_threat_correlations_campaign ON threat_correlations(campaign_id);
CREATE INDEX IF NOT EXISTS idx_threat_feeds_status ON threat_feeds(status);
CREATE INDEX IF NOT EXISTS idx_threat_intelligence_feeds_status ON threat_intelligence_feeds(status);
CREATE INDEX IF NOT EXISTS idx_tlp_classifications_type ON tlp_classifications(data_type);
CREATE INDEX IF NOT EXISTS idx_ttp_execution_metrics_campaign ON ttp_execution_metrics(campaign_id);
CREATE INDEX IF NOT EXISTS idx_ttp_execution_metrics_technique ON ttp_execution_metrics(mitre_technique);
CREATE INDEX IF NOT EXISTS idx_webhook_delivery_log_webhook ON webhook_delivery_log(webhook_id);
CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_campaign ON webhook_subscriptions(campaign_id);

-- Foreign keys emitted after all tables to avoid creation-order failures
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_action_risk_log_campaign_id_campaigns_id') THEN ALTER TABLE "action_risk_log" ADD CONSTRAINT "fk_action_risk_log_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_actions_asset_id_assets_id') THEN ALTER TABLE "actions" ADD CONSTRAINT "fk_actions_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_actions_campaign_id_campaigns_id') THEN ALTER TABLE "actions" ADD CONSTRAINT "fk_actions_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_activity_log_campaign_id_campaigns_id') THEN ALTER TABLE "activity_log" ADD CONSTRAINT "fk_activity_log_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_actor_ttps_actor_id_threat_actors_id') THEN ALTER TABLE "actor_ttps" ADD CONSTRAINT "fk_actor_ttps_actor_id_threat_actors_id" FOREIGN KEY ("actor_id") REFERENCES "threat_actors"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_anomaly_detections_campaign_id_campaigns_id') THEN ALTER TABLE "anomaly_detections" ADD CONSTRAINT "fk_anomaly_detections_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_api_integrations_campaign_id_campaigns_id') THEN ALTER TABLE "api_integrations" ADD CONSTRAINT "fk_api_integrations_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_assets_campaign_id_campaigns_id') THEN ALTER TABLE "assets" ADD CONSTRAINT "fk_assets_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_audit_certification_reports_campaign_id_campaigns_id') THEN ALTER TABLE "audit_certification_reports" ADD CONSTRAINT "fk_audit_certification_reports_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_audit_verification_chain_audit_log_id_immutable_audit_log_id') THEN ALTER TABLE "audit_verification_chain" ADD CONSTRAINT "fk_audit_verification_chain_audit_log_id_immutable_audit_log_id" FOREIGN KEY ("audit_log_id") REFERENCES "immutable_audit_log"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_behavioral_profiles_campaign_id_campaigns_id') THEN ALTER TABLE "behavioral_profiles" ADD CONSTRAINT "fk_behavioral_profiles_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_c2_infrastructure_campaign_id_campaigns_id') THEN ALTER TABLE "c2_infrastructure" ADD CONSTRAINT "fk_c2_infrastructure_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaign_metrics_campaign_id_campaigns_id') THEN ALTER TABLE "campaign_metrics" ADD CONSTRAINT "fk_campaign_metrics_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaign_objectives_created_by_users_id') THEN ALTER TABLE "campaign_objectives" ADD CONSTRAINT "fk_campaign_objectives_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaign_objectives_campaign_id_campaigns_id') THEN ALTER TABLE "campaign_objectives" ADD CONSTRAINT "fk_campaign_objectives_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaign_phase_history_campaign_id_campaigns_id') THEN ALTER TABLE "campaign_phase_history" ADD CONSTRAINT "fk_campaign_phase_history_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaign_reports_campaign_id_campaigns_id') THEN ALTER TABLE "campaign_reports" ADD CONSTRAINT "fk_campaign_reports_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaign_team_assignments_team_id_teams_id') THEN ALTER TABLE "campaign_team_assignments" ADD CONSTRAINT "fk_campaign_team_assignments_team_id_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaign_team_assignments_campaign_id_campaigns_id') THEN ALTER TABLE "campaign_team_assignments" ADD CONSTRAINT "fk_campaign_team_assignments_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campaigns_created_by_users_id') THEN ALTER TABLE "campaigns" ADD CONSTRAINT "fk_campaigns_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_capability_assessment_campaign_id_campaigns_id') THEN ALTER TABLE "capability_assessment" ADD CONSTRAINT "fk_capability_assessment_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_capability_timeline_capability_id_capability_assessment_id') THEN ALTER TABLE "capability_timeline" ADD CONSTRAINT "fk_capability_timeline_capability_id_capability_assessment_id" FOREIGN KEY ("capability_id") REFERENCES "capability_assessment"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_client_reports_campaign_id_campaigns_id') THEN ALTER TABLE "client_reports" ADD CONSTRAINT "fk_client_reports_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cognition_state_cache_updated_by_users_id') THEN ALTER TABLE "cognition_state_cache" ADD CONSTRAINT "fk_cognition_state_cache_updated_by_users_id" FOREIGN KEY ("updated_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cognition_state_cache_campaign_id_campaigns_id') THEN ALTER TABLE "cognition_state_cache" ADD CONSTRAINT "fk_cognition_state_cache_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_collaboration_sessions_created_by_users_id') THEN ALTER TABLE "collaboration_sessions" ADD CONSTRAINT "fk_collaboration_sessions_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_collaboration_sessions_campaign_id_campaigns_id') THEN ALTER TABLE "collaboration_sessions" ADD CONSTRAINT "fk_collaboration_sessions_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_collaborative_changes_operator_id_users_id') THEN ALTER TABLE "collaborative_changes" ADD CONSTRAINT "fk_collaborative_changes_operator_id_users_id" FOREIGN KEY ("operator_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_collaborative_changes_collab_session_id_collaboration_sessions_id') THEN ALTER TABLE "collaborative_changes" ADD CONSTRAINT "fk_collaborative_changes_collab_session_id_collaboration_sessions_id" FOREIGN KEY ("collab_session_id") REFERENCES "collaboration_sessions"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_command_execution_ledger_created_by_users_id') THEN ALTER TABLE "command_execution_ledger" ADD CONSTRAINT "fk_command_execution_ledger_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_command_execution_ledger_asset_id_assets_id') THEN ALTER TABLE "command_execution_ledger" ADD CONSTRAINT "fk_command_execution_ledger_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_command_execution_ledger_campaign_id_campaigns_id') THEN ALTER TABLE "command_execution_ledger" ADD CONSTRAINT "fk_command_execution_ledger_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_compliance_attestations_campaign_id_campaigns_id') THEN ALTER TABLE "compliance_attestations" ADD CONSTRAINT "fk_compliance_attestations_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_compliance_mappings_framework_id_compliance_frameworks_id') THEN ALTER TABLE "compliance_mappings" ADD CONSTRAINT "fk_compliance_mappings_framework_id_compliance_frameworks_id" FOREIGN KEY ("framework_id") REFERENCES "compliance_frameworks"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_compliance_mappings_campaign_id_campaigns_id') THEN ALTER TABLE "compliance_mappings" ADD CONSTRAINT "fk_compliance_mappings_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_compliance_report_mappings_finding_id_findings_id') THEN ALTER TABLE "compliance_report_mappings" ADD CONSTRAINT "fk_compliance_report_mappings_finding_id_findings_id" FOREIGN KEY ("finding_id") REFERENCES "findings"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_compliance_report_mappings_campaign_id_campaigns_id') THEN ALTER TABLE "compliance_report_mappings" ADD CONSTRAINT "fk_compliance_report_mappings_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_coordination_logs_target_team_id_teams_id') THEN ALTER TABLE "coordination_logs" ADD CONSTRAINT "fk_coordination_logs_target_team_id_teams_id" FOREIGN KEY ("target_team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_coordination_logs_source_team_id_teams_id') THEN ALTER TABLE "coordination_logs" ADD CONSTRAINT "fk_coordination_logs_source_team_id_teams_id" FOREIGN KEY ("source_team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_credential_state_credential_id_credentials_id') THEN ALTER TABLE "credential_state" ADD CONSTRAINT "fk_credential_state_credential_id_credentials_id" FOREIGN KEY ("credential_id") REFERENCES "credentials"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_credentials_captured_by_users_id') THEN ALTER TABLE "credentials" ADD CONSTRAINT "fk_credentials_captured_by_users_id" FOREIGN KEY ("captured_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_credentials_asset_id_assets_id') THEN ALTER TABLE "credentials" ADD CONSTRAINT "fk_credentials_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_credentials_campaign_id_campaigns_id') THEN ALTER TABLE "credentials" ADD CONSTRAINT "fk_credentials_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_data_sharing_policies_target_team_id_teams_id') THEN ALTER TABLE "data_sharing_policies" ADD CONSTRAINT "fk_data_sharing_policies_target_team_id_teams_id" FOREIGN KEY ("target_team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_data_sharing_policies_source_team_id_teams_id') THEN ALTER TABLE "data_sharing_policies" ADD CONSTRAINT "fk_data_sharing_policies_source_team_id_teams_id" FOREIGN KEY ("source_team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_defense_prediction_campaign_id_campaigns_id') THEN ALTER TABLE "defense_prediction" ADD CONSTRAINT "fk_defense_prediction_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_detection_events_asset_id_assets_id') THEN ALTER TABLE "detection_events" ADD CONSTRAINT "fk_detection_events_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_detection_events_campaign_id_campaigns_id') THEN ALTER TABLE "detection_events" ADD CONSTRAINT "fk_detection_events_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_detection_pressure_history_campaign_id_campaigns_id') THEN ALTER TABLE "detection_pressure_history" ADD CONSTRAINT "fk_detection_pressure_history_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_engagement_reports_campaign_id_campaigns_id') THEN ALTER TABLE "engagement_reports" ADD CONSTRAINT "fk_engagement_reports_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_enrichment_data_ioc_id_indicators_of_compromise_id') THEN ALTER TABLE "enrichment_data" ADD CONSTRAINT "fk_enrichment_data_ioc_id_indicators_of_compromise_id" FOREIGN KEY ("ioc_id") REFERENCES "indicators_of_compromise"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evasion_assessment_detection_event_id_detection_events_id') THEN ALTER TABLE "evasion_assessment" ADD CONSTRAINT "fk_evasion_assessment_detection_event_id_detection_events_id" FOREIGN KEY ("detection_event_id") REFERENCES "detection_events"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evasion_assessment_campaign_id_campaigns_id') THEN ALTER TABLE "evasion_assessment" ADD CONSTRAINT "fk_evasion_assessment_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidence_items_approved_by_users_id') THEN ALTER TABLE "evidence_items" ADD CONSTRAINT "fk_evidence_items_approved_by_users_id" FOREIGN KEY ("approved_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidence_items_collected_by_users_id') THEN ALTER TABLE "evidence_items" ADD CONSTRAINT "fk_evidence_items_collected_by_users_id" FOREIGN KEY ("collected_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidence_items_finding_id_findings_id') THEN ALTER TABLE "evidence_items" ADD CONSTRAINT "fk_evidence_items_finding_id_findings_id" FOREIGN KEY ("finding_id") REFERENCES "findings"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidence_items_campaign_id_campaigns_id') THEN ALTER TABLE "evidence_items" ADD CONSTRAINT "fk_evidence_items_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidence_manifest_entries_evidence_id_evidence_items_id') THEN ALTER TABLE "evidence_manifest_entries" ADD CONSTRAINT "fk_evidence_manifest_entries_evidence_id_evidence_items_id" FOREIGN KEY ("evidence_id") REFERENCES "evidence_items"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidence_manifest_entries_manifest_id_evidence_manifests_id') THEN ALTER TABLE "evidence_manifest_entries" ADD CONSTRAINT "fk_evidence_manifest_entries_manifest_id_evidence_manifests_id" FOREIGN KEY ("manifest_id") REFERENCES "evidence_manifests"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidence_manifests_campaign_id_campaigns_id') THEN ALTER TABLE "evidence_manifests" ADD CONSTRAINT "fk_evidence_manifests_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_finding_summaries_finding_id_findings_id') THEN ALTER TABLE "finding_summaries" ADD CONSTRAINT "fk_finding_summaries_finding_id_findings_id" FOREIGN KEY ("finding_id") REFERENCES "findings"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_indicators_of_compromise_threat_actor_id_threat_actors_id') THEN ALTER TABLE "indicators_of_compromise" ADD CONSTRAINT "fk_indicators_of_compromise_threat_actor_id_threat_actors_id" FOREIGN KEY ("threat_actor_id") REFERENCES "threat_actors"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_indicators_of_compromise_source_feed_id_threat_feeds_id') THEN ALTER TABLE "indicators_of_compromise" ADD CONSTRAINT "fk_indicators_of_compromise_source_feed_id_threat_feeds_id" FOREIGN KEY ("source_feed_id") REFERENCES "threat_feeds"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_indicators_of_compromise_campaign_id_campaigns_id') THEN ALTER TABLE "indicators_of_compromise" ADD CONSTRAINT "fk_indicators_of_compromise_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_intel_indicators_feed_id_threat_intelligence_feeds_id') THEN ALTER TABLE "intel_indicators" ADD CONSTRAINT "fk_intel_indicators_feed_id_threat_intelligence_feeds_id" FOREIGN KEY ("feed_id") REFERENCES "threat_intelligence_feeds"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_intel_indicators_campaign_id_campaigns_id') THEN ALTER TABLE "intel_indicators" ADD CONSTRAINT "fk_intel_indicators_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_intelligence_archive_archived_by_users_id') THEN ALTER TABLE "intelligence_archive" ADD CONSTRAINT "fk_intelligence_archive_archived_by_users_id" FOREIGN KEY ("archived_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_intelligence_archive_campaign_id_campaigns_id') THEN ALTER TABLE "intelligence_archive" ADD CONSTRAINT "fk_intelligence_archive_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_intelligence_archive_actor_id_threat_actors_id') THEN ALTER TABLE "intelligence_archive" ADD CONSTRAINT "fk_intelligence_archive_actor_id_threat_actors_id" FOREIGN KEY ("actor_id") REFERENCES "threat_actors"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_loot_asset_id_assets_id') THEN ALTER TABLE "loot" ADD CONSTRAINT "fk_loot_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_loot_campaign_id_campaigns_id') THEN ALTER TABLE "loot" ADD CONSTRAINT "fk_loot_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_objective_progress_objective_id_campaign_objectives_id') THEN ALTER TABLE "objective_progress" ADD CONSTRAINT "fk_objective_progress_objective_id_campaign_objectives_id" FOREIGN KEY ("objective_id") REFERENCES "campaign_objectives"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operation_phases_entered_by_users_id') THEN ALTER TABLE "operation_phases" ADD CONSTRAINT "fk_operation_phases_entered_by_users_id" FOREIGN KEY ("entered_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operation_phases_campaign_id_campaigns_id') THEN ALTER TABLE "operation_phases" ADD CONSTRAINT "fk_operation_phases_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operator_performance_team_id_teams_id') THEN ALTER TABLE "operator_performance" ADD CONSTRAINT "fk_operator_performance_team_id_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operator_performance_user_id_users_id') THEN ALTER TABLE "operator_performance" ADD CONSTRAINT "fk_operator_performance_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operator_presence_operator_id_users_id') THEN ALTER TABLE "operator_presence" ADD CONSTRAINT "fk_operator_presence_operator_id_users_id" FOREIGN KEY ("operator_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operator_presence_collab_session_id_collaboration_sessions_id') THEN ALTER TABLE "operator_presence" ADD CONSTRAINT "fk_operator_presence_collab_session_id_collaboration_sessions_id" FOREIGN KEY ("collab_session_id") REFERENCES "collaboration_sessions"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operator_tempo_metrics_operator_id_users_id') THEN ALTER TABLE "operator_tempo_metrics" ADD CONSTRAINT "fk_operator_tempo_metrics_operator_id_users_id" FOREIGN KEY ("operator_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operator_tempo_metrics_campaign_id_campaigns_id') THEN ALTER TABLE "operator_tempo_metrics" ADD CONSTRAINT "fk_operator_tempo_metrics_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_opsec_rules_created_by_users_id') THEN ALTER TABLE "opsec_rules" ADD CONSTRAINT "fk_opsec_rules_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_persistence_registry_asset_id_assets_id') THEN ALTER TABLE "persistence_registry" ADD CONSTRAINT "fk_persistence_registry_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_persistence_registry_campaign_id_campaigns_id') THEN ALTER TABLE "persistence_registry" ADD CONSTRAINT "fk_persistence_registry_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_persistence_verification_log_persistence_id_persistence_registry_id') THEN ALTER TABLE "persistence_verification_log" ADD CONSTRAINT "fk_persistence_verification_log_persistence_id_persistence_registry_id" FOREIGN KEY ("persistence_id") REFERENCES "persistence_registry"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_projects_group_id_groups_id') THEN ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_group_id_groups_id" FOREIGN KEY ("group_id") REFERENCES "groups"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_purge_operations_policy_id_retention_policies_id') THEN ALTER TABLE "purge_operations" ADD CONSTRAINT "fk_purge_operations_policy_id_retention_policies_id" FOREIGN KEY ("policy_id") REFERENCES "retention_policies"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_re_authentication_log_user_id_users_id') THEN ALTER TABLE "re_authentication_log" ADD CONSTRAINT "fk_re_authentication_log_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_real_time_alerts_campaign_id_campaigns_id') THEN ALTER TABLE "real_time_alerts" ADD CONSTRAINT "fk_real_time_alerts_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recommendation_history_created_by_users_id') THEN ALTER TABLE "recommendation_history" ADD CONSTRAINT "fk_recommendation_history_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recommendation_history_campaign_id_campaigns_id') THEN ALTER TABLE "recommendation_history" ADD CONSTRAINT "fk_recommendation_history_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_relations_campaign_id_campaigns_id') THEN ALTER TABLE "relations" ADD CONSTRAINT "fk_relations_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_relationships_created_by_users_id') THEN ALTER TABLE "relationships" ADD CONSTRAINT "fk_relationships_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_relationships_campaign_id_campaigns_id') THEN ALTER TABLE "relationships" ADD CONSTRAINT "fk_relationships_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_remediation_actions_asset_id_assets_id') THEN ALTER TABLE "remediation_actions" ADD CONSTRAINT "fk_remediation_actions_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_remediation_actions_campaign_id_campaigns_id') THEN ALTER TABLE "remediation_actions" ADD CONSTRAINT "fk_remediation_actions_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_remediation_impact_remediation_id_remediation_actions_id') THEN ALTER TABLE "remediation_impact" ADD CONSTRAINT "fk_remediation_impact_remediation_id_remediation_actions_id" FOREIGN KEY ("remediation_id") REFERENCES "remediation_actions"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_replay_events_campaign_id_campaigns_id') THEN ALTER TABLE "replay_events" ADD CONSTRAINT "fk_replay_events_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_report_history_report_schedule_id_report_schedules_id') THEN ALTER TABLE "report_history" ADD CONSTRAINT "fk_report_history_report_schedule_id_report_schedules_id" FOREIGN KEY ("report_schedule_id") REFERENCES "report_schedules"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_report_schedules_campaign_id_campaigns_id') THEN ALTER TABLE "report_schedules" ADD CONSTRAINT "fk_report_schedules_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_report_versions_report_id_campaign_reports_id') THEN ALTER TABLE "report_versions" ADD CONSTRAINT "fk_report_versions_report_id_campaign_reports_id" FOREIGN KEY ("report_id") REFERENCES "campaign_reports"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_risk_scores_finding_id_findings_id') THEN ALTER TABLE "risk_scores" ADD CONSTRAINT "fk_risk_scores_finding_id_findings_id" FOREIGN KEY ("finding_id") REFERENCES "findings"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_risk_scores_campaign_id_campaigns_id') THEN ALTER TABLE "risk_scores" ADD CONSTRAINT "fk_risk_scores_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_scheduled_tasks_created_by_users_id') THEN ALTER TABLE "scheduled_tasks" ADD CONSTRAINT "fk_scheduled_tasks_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_scheduled_tasks_task_template_id_task_templates_id') THEN ALTER TABLE "scheduled_tasks" ADD CONSTRAINT "fk_scheduled_tasks_task_template_id_task_templates_id" FOREIGN KEY ("task_template_id") REFERENCES "task_templates"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_scheduled_tasks_campaign_id_campaigns_id') THEN ALTER TABLE "scheduled_tasks" ADD CONSTRAINT "fk_scheduled_tasks_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sensitive_field_audit_accessed_by_users_id') THEN ALTER TABLE "sensitive_field_audit" ADD CONSTRAINT "fk_sensitive_field_audit_accessed_by_users_id" FOREIGN KEY ("accessed_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_lifecycle_asset_id_assets_id') THEN ALTER TABLE "session_lifecycle" ADD CONSTRAINT "fk_session_lifecycle_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_lifecycle_campaign_id_campaigns_id') THEN ALTER TABLE "session_lifecycle" ADD CONSTRAINT "fk_session_lifecycle_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_management_user_id_users_id') THEN ALTER TABLE "session_management" ADD CONSTRAINT "fk_session_management_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sessions_user_id_users_id') THEN ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sessions_ops_asset_id_assets_id') THEN ALTER TABLE "sessions_ops" ADD CONSTRAINT "fk_sessions_ops_asset_id_assets_id" FOREIGN KEY ("asset_id") REFERENCES "assets"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sessions_ops_campaign_id_campaigns_id') THEN ALTER TABLE "sessions_ops" ADD CONSTRAINT "fk_sessions_ops_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_target_lock_diffs_reviewed_by_users_id') THEN ALTER TABLE "target_lock_diffs" ADD CONSTRAINT "fk_target_lock_diffs_reviewed_by_users_id" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_target_lock_diffs_lock_id_target_locks_id') THEN ALTER TABLE "target_lock_diffs" ADD CONSTRAINT "fk_target_lock_diffs_lock_id_target_locks_id" FOREIGN KEY ("lock_id") REFERENCES "target_locks"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_target_locks_operator_id_users_id') THEN ALTER TABLE "target_locks" ADD CONSTRAINT "fk_target_locks_operator_id_users_id" FOREIGN KEY ("operator_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_target_locks_campaign_id_campaigns_id') THEN ALTER TABLE "target_locks" ADD CONSTRAINT "fk_target_locks_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_execution_log_scheduled_task_id_scheduled_tasks_id') THEN ALTER TABLE "task_execution_log" ADD CONSTRAINT "fk_task_execution_log_scheduled_task_id_scheduled_tasks_id" FOREIGN KEY ("scheduled_task_id") REFERENCES "scheduled_tasks"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_templates_created_by_users_id') THEN ALTER TABLE "task_templates" ADD CONSTRAINT "fk_task_templates_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_templates_campaign_id_campaigns_id') THEN ALTER TABLE "task_templates" ADD CONSTRAINT "fk_task_templates_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_team_intelligence_pools_team_id_teams_id') THEN ALTER TABLE "team_intelligence_pools" ADD CONSTRAINT "fk_team_intelligence_pools_team_id_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_team_members_user_id_users_id') THEN ALTER TABLE "team_members" ADD CONSTRAINT "fk_team_members_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_team_members_team_id_teams_id') THEN ALTER TABLE "team_members" ADD CONSTRAINT "fk_team_members_team_id_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_team_metrics_team_id_teams_id') THEN ALTER TABLE "team_metrics" ADD CONSTRAINT "fk_team_metrics_team_id_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_team_permissions_user_id_users_id') THEN ALTER TABLE "team_permissions" ADD CONSTRAINT "fk_team_permissions_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_team_permissions_team_id_teams_id') THEN ALTER TABLE "team_permissions" ADD CONSTRAINT "fk_team_permissions_team_id_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_team_roles_team_id_teams_id') THEN ALTER TABLE "team_roles" ADD CONSTRAINT "fk_team_roles_team_id_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teams_lead_operator_id_users_id') THEN ALTER TABLE "teams" ADD CONSTRAINT "fk_teams_lead_operator_id_users_id" FOREIGN KEY ("lead_operator_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_technique_patterns_campaign_id_campaigns_id') THEN ALTER TABLE "technique_patterns" ADD CONSTRAINT "fk_technique_patterns_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_threat_actors_created_by_users_id') THEN ALTER TABLE "threat_actors" ADD CONSTRAINT "fk_threat_actors_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_threat_correlations_correlated_by_users_id') THEN ALTER TABLE "threat_correlations" ADD CONSTRAINT "fk_threat_correlations_correlated_by_users_id" FOREIGN KEY ("correlated_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_threat_correlations_campaign_id_campaigns_id') THEN ALTER TABLE "threat_correlations" ADD CONSTRAINT "fk_threat_correlations_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_threat_feeds_created_by_users_id') THEN ALTER TABLE "threat_feeds" ADD CONSTRAINT "fk_threat_feeds_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tlp_classifications_created_by_users_id') THEN ALTER TABLE "tlp_classifications" ADD CONSTRAINT "fk_tlp_classifications_created_by_users_id" FOREIGN KEY ("created_by") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ttp_execution_metrics_campaign_id_campaigns_id') THEN ALTER TABLE "ttp_execution_metrics" ADD CONSTRAINT "fk_ttp_execution_metrics_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_capabilities_user_id_users_id') THEN ALTER TABLE "user_capabilities" ADD CONSTRAINT "fk_user_capabilities_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_group_id_groups_id') THEN ALTER TABLE "users" ADD CONSTRAINT "fk_users_group_id_groups_id" FOREIGN KEY ("group_id") REFERENCES "groups"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_webhook_delivery_log_webhook_id_webhook_subscriptions_id') THEN ALTER TABLE "webhook_delivery_log" ADD CONSTRAINT "fk_webhook_delivery_log_webhook_id_webhook_subscriptions_id" FOREIGN KEY ("webhook_id") REFERENCES "webhook_subscriptions"("id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_webhook_subscriptions_campaign_id_campaigns_id') THEN ALTER TABLE "webhook_subscriptions" ADD CONSTRAINT "fk_webhook_subscriptions_campaign_id_campaigns_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id"); END IF; END $$;

CREATE OR REPLACE FUNCTION prevent_mutation_when_immutable() RETURNS trigger AS $$
BEGIN
    IF OLD.immutable = 1 THEN
        RAISE EXCEPTION 'immutable row cannot be modified';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='evidence_items' AND column_name='immutable') THEN
    DROP TRIGGER IF EXISTS trg_evidence_items_immutable_update ON evidence_items;
    CREATE TRIGGER trg_evidence_items_immutable_update BEFORE UPDATE OR DELETE ON evidence_items
    FOR EACH ROW EXECUTE FUNCTION prevent_mutation_when_immutable();
END IF;
END $$;

CREATE TABLE IF NOT EXISTS "legal_acceptances" (
    "id" BIGSERIAL,
    "user_id" BIGINT,
    "username" TEXT NOT NULL,
    "tenant_id" UUID,
    "deployment_mode" TEXT NOT NULL,
    "document_hash" TEXT NOT NULL,
    "legal_version" TEXT NOT NULL,
    "accepted" BOOLEAN NOT NULL DEFAULT TRUE,
    "accepted_at" TIMESTAMPTZ NOT NULL,
    "ip_address" TEXT DEFAULT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_legal_acceptances_user_mode_version"
    ON "legal_acceptances" ("username", "deployment_mode", "legal_version");

CREATE INDEX IF NOT EXISTS "idx_legal_acceptances_hash_version"
    ON "legal_acceptances" ("document_hash", "legal_version");
